// <auto-generated />
using System;
using HackathonLime.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HackathonLime.DAL.Migrations
{
    [DbContext(typeof(HackathonLimeDbContext))]
    [Migration("20231215090119_ReadyMadeTemplate")]
    partial class ReadyMadeTemplate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("FilmIdSequence")
                .HasMin(1L)
                .HasMax(100000L);

            modelBuilder.Entity("HackathonLime.Domain.OnlineCinema.FilmModel", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"FilmIdSequence\"')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FilmRaiting")
                        .HasColumnType("double precision");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RentalDuration")
                        .HasColumnType("integer");

                    b.Property<double>("RentalRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FilmId");

                    b.ToTable("Film", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
