# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  hackathonlimeapplication:
    image: hackathonlimeapplication
    build:
      context: .
      dockerfile: HackathonLime.Application/Dockerfile
    ports:
      - 5000:5000
